In [1]:
import pandas as pd
import numpy as np

In [2]:
sub53 = pd.read_csv("goodsubs\\submission53.csv") # 0.9852
sub54 = pd.read_csv("submissions\\submission54.csv") # 0.9862
sub56 = pd.read_csv("goodsubs\\submission56.csv") # 0.9848
sub58 = pd.read_csv("submissions\\submission58.csv") # 0.9867
lstm13 = pd.read_csv("submissions\\lstm13.csv") # 0.9840
lstm14 = pd.read_csv("submissions\\lstm14.csv") # 0.9836
lstm16 = pd.read_csv("submissions\\lstm16.csv") # 0.9841
lstm19 = pd.read_csv("submissions\\lstm19.csv") # 0.9851
lstm20 = pd.read_csv("submissions\\lstm20.csv") # 0.9845
lstm21 = pd.read_csv("submissions\\lstm21.csv") # 0.9853
gru5 = pd.read_csv("submissions\\gru5.csv") # 0.9849
gru7 = pd.read_csv("submissions\\gru7.csv") # 0.9842
gru8 = pd.read_csv("submissions\\gru8.csv") # 0.9854
grucnn = pd.read_csv("submissions\\grucnn1.csv") # 
cnn = pd.read_csv("submissions\\cnn1.csv") # 
superblend = pd.read_csv("superblend_1.csv") # 0.9854
hyperblend = pd.read_csv("hight_of_blend_v2.csv") # 0.9861

In [13]:
sub61 = pd.read_csv("submissions\\submission61.csv") # 0.9867
sub64 = pd.read_csv("submissions\\submission64.csv") # 
sub65 = pd.read_csv("submissions\\submission65.csv") # 
sub67 = pd.read_csv("submissions\\submission65.csv") # 

In [4]:
sub45 = pd.read_csv("submissions\\submission45.csv") # 0.9808

In [5]:
lstm12 = pd.read_csv("submissions\\lstm12.csv") # 0.9827

In [6]:
sub66 = pd.read_csv("submissions\\submission66.csv")

In [10]:
blend = sub61.copy()

In [11]:
labels = [c for c in sub61.columns][1:]

In [58]:
blend[labels] = (9*sub61[labels] + lstm12[labels] + lstm13[labels] + lstm14[labels] + lstm16[labels] + lstm19[labels] + lstm20[labels] + lstm21[labels] + gru5[labels] + hyperblend[labels]) / 18

In [59]:
blend.to_csv("9sub61_lstm12131416192021_gru5_hyperblend.csv", index=False)

In [7]:
from scipy.stats import pearsonr

In [8]:
def pearson_pvalues(dataset1, dataset2):
    correlations = []
    for label in labels:
        corr = pearsonr(dataset1[label], dataset2[label])[0]
        correlations.append(corr)
    print(np.mean(correlations))

In [15]:
pearson_pvalues(sub61, lstm12)
pearson_pvalues(sub61, lstm13)
pearson_pvalues(sub61, lstm14)
pearson_pvalues(sub61, lstm16)
pearson_pvalues(sub61, lstm19)
pearson_pvalues(sub61, lstm20)
pearson_pvalues(sub61, lstm21)
pearson_pvalues(sub61, gru5)
pearson_pvalues(sub61, gru7)
pearson_pvalues(sub61, gru8)
pearson_pvalues(sub61, grucnn)
pearson_pvalues(sub61, superblend)
pearson_pvalues(sub61, hyperblend)

0.9017021522484269
0.9218254643975013
0.9440469435736748
0.9398031316959274
0.959775916044605
0.9440645741361152
0.9545198169793715
0.9392487296800768
0.9477686391093796
0.956724640322009
0.938174769786715
0.9599538761135232
0.9537601521770722


In [16]:
pearson_pvalues(sub67, lstm12)
pearson_pvalues(sub67, lstm13)
pearson_pvalues(sub67, lstm14)
pearson_pvalues(sub67, lstm16)
pearson_pvalues(sub67, lstm19)
pearson_pvalues(sub67, lstm20)
pearson_pvalues(sub67, lstm21)
pearson_pvalues(sub67, gru5)
pearson_pvalues(sub67, gru7)
pearson_pvalues(sub67, gru8)
pearson_pvalues(sub67, grucnn)
pearson_pvalues(sub67, superblend)
pearson_pvalues(sub67, hyperblend)

0.9057156037466839
0.9269048014828588
0.9452109942407013
0.9442283136516015
0.9623835628522809
0.9487472916986771
0.9593123529684814
0.9518305994562294
0.9538139685551233
0.9636817489550435
0.9459755517508294
0.9593302905107614
0.9583517964861605


In [12]:
pearson_pvalues(sub66, lstm12)

0.9144019104891715


In [65]:
x = [1,2,3]

In [66]:
y = [1,1,0]

In [68]:
x = np.array(x)
y = np.array(y)

In [69]:
x*y

array([1, 2, 0])

In [70]:
x = [[1,2,3],[4,5,6]]

In [71]:
x = np.array(x)

In [72]:
x*y

array([[1, 2, 0],
       [4, 5, 0]])

In [73]:
x.dot(y)

array([3, 9])